src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Photo $photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: PhotoRepository::class)]
#[Vich\Uploadable]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Vich\UploadableField(mapping: 'uploaded_photos',  fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null; 
    
    #[ORM\Column(length: 255)]
    private ?string $imageName = null;

    #[ORM\Column(type: 'integer')]
    private ?int $imageSize = null;
    
    #[ORM\Column]
    private ?\DateTimeImmutable $post_at = null;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'photo', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPostAt(): ?string
    {
        return date_format($this->post_at, 'd-m-Y H:i:s');
    }

    public function setPostAt(\DateTimeImmutable $post_at): self
    {
        $this->post_at = $post_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void {
        $this->imageFile = $imageFile;
        
        if (null !== $imageFile ){
            $this->post_at = new \DateTimeImmutable();
        }
    }
  
    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function setImageSize(?int $imageSize): self
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPhoto($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPhoto() === $this) {
                $comment->setPhoto(null);
            }
        }

        return $this;
    }

}

src/Form/Photo/CommentType.php
<?php

namespace App\Form\Photo;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class, ['label' => 'Votre commentaire'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Form/Photo/NewPhotoType.php
<?php

namespace App\Form\Photo;

use App\Entity\Photo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class NewPhotoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ['label' => 'Nom de la photo '])
            ->add('imageFile', VichImageType::class, ['label' => 'Votre photo '])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Photo::class,
        ]);
    }
}

src/Controller/PhotoController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Photo;
use App\Form\Photo\CommentType;
use App\Form\Photo\NewPhotoType;
use App\Repository\PhotoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

class PhotoController extends AbstractController
{
    #[Route('/', name: 'photo.list')]
    public function list(PhotoRepository $photoRepository): Response
    {
        $photos = $photoRepository->findAll();

        return $this->render('photo/list.html.twig', [
            'photos' => $photos,
        ]);
    }

    #[Route('/photo/show/{id}', name : 'photo.show')]
    public function show(Photo $photo, Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if ($user) {
            $comment = new Comment();
            $form = $this->createForm(CommentType::class, $comment);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $comment->setUser($user)
                        ->setPhoto($photo)
                        ->setCreateAt(new \DateTimeImmutable());
                $entityManager->persist($comment);
                $entityManager->flush();

                return $this->redirectToRoute('photo.show', ['id' => $photo->getId()]);
            } else {
                return $this->render('photo/show.html.twig', [
                    'photo' => $photo,
                    'commentForm' => $form->createView(),
                ]);
            }
            
        }
        return $this->render('photo/show.html.twig', [
            'photo' => $photo,
        ]);
    }

    #[Route('/photo/manage', name : 'photo.manage')]
    public function manage(): Response
    {
        $user = $this->getUser();
        $photos = $user->getPhotos();

        return $this->render('photo/manage.html.twig', [
            'photos' => $photos,
        ]);
    }

    #[Route('/photo/delete/{id}', name : 'photo.delete')]
    public function delete(Photo $photo, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($photo);
        $entityManager->flush();

        return $this->redirectToRoute('photo.manage');
    }

    #[Route('/photo/new', name : 'photo.new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $photo = new Photo();
        $form = $this->createForm(NewPhotoType::class, $photo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $photo->setUser($this->getUser());
            $photo->setPostAt(new \DateTimeImmutable());
            $entityManager->persist($photo);
            $entityManager->flush();
            $this->addFlash(
                'success',
                'Votre photo à été uploadée'
            );
    
            return $this->redirectToRoute('photo.manage');
        }

        return $this->render('photo/new.html.twig', [
            'newForm' => $form->createView(),
        ]);
    }

}

templates/photo/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
        <h2>Les photos</h2>
        <div class="row flex">
            {% for photo in photos %}
                <div class="col-3">
                    <div class="card">
                        <img class="card-img-top" src="{{ vich_uploader_asset(photo, 'imageFile') }}" alt="img defaut">
                        <div class="card-boby">
                            <h5 class="card-title"><a href="{{ path('photo.show', {id: photo.id}) }}">{{ photo.title }}</a></h5>
                            <h5>Postée par : {{ photo.user.pseudo }}</h5>
                            <p class="card-text">Postée le : {{ photo.postAt }}</p>
                            <div class="text-primary" style="font-weight: bold; font-size: 1.2rem;">commentaires : {{ photo.comments|length }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/photo/manage.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">
			{{ message }}
		</div>
	{% endfor %}

	<div class="container">
		<h2>Liste de vos photos</h2>
		<div class="row flex">

			<div class="col-8">
				<table class="table table-striped">
					<tr>
						<th>Titre</th>
						<th>Date</th>
						<th>nb commentaires</th>
						<th></th>
					</tr>
                    {% for photo in photos %}
					<tr>
						<td>{{ photo.title }}</td>
						<td>{{ photo.postAt }}</td>
						<td>{{ photo.comments|length }}</td>
						<td>
							<a href="{{ path("photo.delete", {id: photo.id}) }}" class="btn btn-secondary">
								Supprimer</a>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>

		<div class="col-4">
			<a href="{{ path('photo.new') }}" class="btn btn-primary">Ajouter une photo</a>
		</div>
	</div>
</div>{% endblock %}

templates/photo/new.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<style>
    form {
        margin-left: 20%;
        width: 50%;
    }
</style>
{% endblock %}

{% block body %}
    <h1>Ajout d'une photo</h1>

    {{ form_start(newForm) }}
        {{ form_row(newForm.title) }}
        {{ form_row(newForm.imageFile) }}

        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {{ form_end(newForm) }}
{% endblock %}

templates/photo/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<img src="{{ vich_uploader_asset(photo, 'imageFile')  }}" alt="card-img-top" style="width: 100%; height: auto;">
				</div>
				<div class="col-md-4">
					<h1>{{ photo.title }}</h1>
					<h2>Postée le :
						{{ photo.postAt|date("d/m/Y") }}</h2>
					<div class="text-primary" style="font-weight: bold; font-size: 1.3rem">
						<p>Par :
							{{ photo.user.pseudo }}</p>
					</div>
					{% if app.user %}
						<h3>Mettre un commentaire</h3>
						<div id="commentForm" class="mt-4">
						    {{ form_start(commentForm) }}
								<div class="row">
									<div class="col">{{ form_row(commentForm.content) }}</div>
								</div>
								<div class="form-group">
									<button class="btn btn-primary">Envoyer</button>
								</div>
                            {{ form_end(commentForm) }}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-8">
				<h2>Commentaires</h2>
				<table class="table table-striped">
					<tr>
						<th>Commentée par</th>
						<th>Date</th>
						<th>Commentaire</th>
					</tr>
					{% for comment in photo.comments %}
					<tr>
						<td>{{ comment.user.pseudo }}</td>
						<td>{{ comment.createAt|date("d/m/Y") }}</td>
						<td>{{ comment.content }}</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
{% endblock %}